### ISSUE TITLE
access_token is None

### ISSUE THREAD

**Issue by jasonmaoverlord** [007gzs/dingtalk-sdk#1]
when I try to use dingtalk like this:
from dingtalk import SecretClient
def get_sub_dept_id_list(corp_id, corp_secret):
    client = SecretClient(corp_id, corp_secret)
    sub_dept_list = client.department.list_ids()
    return sub_dept_list

there is a problem:
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dingtalk/client/__init__.py", line 83, in _handle_pre_request
    uri = '%s%saccess_token=%s' % (uri, '&' if '?' in uri else '?', self.access_token)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dingtalk/client/__init__.py", line 43, in access_token
    token = ret['access_token']
TypeError: 'NoneType' object is not subscriptable

the access_token seems to be None

but I am sure the corp_id and corp_secret is working when I try like this:
def get_access_token(corp_id, corp_secret):
    url = 'https://oapi.dingtalk.com/gettoken?corpid={}&corpsecret={}'.format(corp_id, corp_secret)
    request = urllib.request.Request(url)
    response = urllib.request.urlopen(request)
    response_str = response.read().decode("utf-8")
    response_dict = json.loads(response_str)
    error_code_key = "errcode"
    error_message = "errmsg"
    access_token_key = "access_token"
    if response_dict[error_code_key] == 0 and response_dict[error_message] == "ok":
        return response_dict[access_token_key]
    else:
        return None

I get the access_token

if there are somthing wrong , please tell me , thank you very much!!

**Comment by 007gzs** [comment]
I have fixed the bug please try `pip install ”dingtalk-sdk>=1.1.4“`

**Comment by jasonmaoverlord** [comment]
Thank you very much ,last night I found "json_loads()", so I changed it to "json.loads()",It worked well. if there are somthing else haved been changed in 1.1.4. please inform me. Thank you again.

**Comment by 007gzs** [comment]
https://github.com/007gzs/dingtalk-sdk/commit/59435e1bed0b15eefb8abf6fada3e0ce62217636
json_loads is added in 1.1.3 but i forgot return ...
json_loads set default object_hook ObjectDict, result data can use res.xxx and res['xxx']
if you change json_loads to json.loads , it same to 1.1.2

**Comment by jasonmaoverlord** [comment]
I get it. Thank you
