### ISSUE TITLE
cannot import name 'AppKeyClient' from 'dingtalk' 

### ISSUE THREAD

**Issue by piofoiq** [007gzs/dingtalk-sdk#10]
换了pycharm和vs，本地环境还是线上环境，都是一个问题，一开始还能执行成功，过一会就不行了，开始报错，不知道什么原因？
Exception has occurred: ImportError
cannot import name 'AppKeyClient' from 'dingtalk' (c:\Users\zuyukun\Desktop\Dingtalk\code\dingtalk.py)
  File "C:\Users\zuyukun\Desktop\Dingtalk\code\dingtalk.py", line 1, in <module>
    from dingtalk import  AppKeyClient, SecretClient
  File "C:\Users\zuyukun\Desktop\Dingtalk\code\dingtalk.py", line 1, in <module>
    from dingtalk import  AppKeyClient, SecretClient

**Comment by 007gzs** [comment]
文件名不要用dingtalk.py，和SDK库路径冲突
