### ISSUE TITLE
异步发送消息报错

### ISSUE THREAD

**Issue by swxs** [007gzs/dingtalk-sdk#12]
相同的消息内容异步发送消息会报错， 同步的不会
具体如下：
同步：
![image](https://user-images.githubusercontent.com/18203761/56176473-c7990580-602d-11e9-8a81-1596591b9888.png)
异步：
![image](https://user-images.githubusercontent.com/18203761/56176486-d2ec3100-602d-11e9-9753-9afd22df33c9.png)

**Comment by 007gzs** [comment]
原来的异步发送接口变更导致错误，后面统一梳理下新接口，报错message没有信息问题已经在1.2.3修复

**Comment by 007gzs** [comment]
1.2.6 版本中增加 `client.message.asyncsend_v2`
