### ISSUE TITLE
发送工作通知消息无法正常工作

### ISSUE THREAD

**Issue by iwenli** [007gzs/dingtalk-sdk#14]
https://open-doc.dingtalk.com/microapp/serverapi2/pgoxpy 发送通知通知文档

client.message.asyncsend(msg, 'xxx', ['xxx']) 异常

**Comment by 007gzs** [comment]
1.2.5版本中增加 `client.message.asyncsend_v2`

**Comment by cdzwm** [comment]
是不正常.
我这么发送可以: 
client.top_request("dingtalk.oapi.message.corpconversation.asyncsend_v2", {'userid_list': '234324234324234', 'agent_id': agent_id, 'msg': {'msgtype':'text', 'text':{'content':'message'}}})
