### ISSUE TITLE
使用TbDingDing(DingTalkBaseAPI)里的接口提示没有权限

### ISSUE THREAD

**Issue by niulinlnc** [007gzs/dingtalk-sdk#18]
如题，是这些接口没开放吗？提示没有权限！

**Comment by 007gzs** [comment]
TbDingDing ？没有这个类吧

**Comment by 007gzs** [comment]
哦，这个是自动从top接口文档生成的代码，是当时有一些新的接口没来得及实现，有些可能不是供钉钉用的。你使用的确认是钉钉相关的接口提示没权限么？

**Comment by niulinlnc** [comment]
我试了钉钉里智能硬件（M2智能前台）获取人脸的api，提示没权限。

**Comment by 007gzs** [comment]
这个在钉钉官网里有文档么

**Comment by niulinlnc** [comment]
https://open-doc.dingtalk.com/docs/api_list.htm?cid=20836
网上搜出来的，官方没显示出来。

**Comment by 007gzs** [comment]
我就是从这爬的，这些应该是阿里所有top接口，可能是供内部使用的，你可以发个工单问下钉钉，就说你按文档请求，放回权限错误，看看他们怎么反馈

**Comment by niulinlnc** [comment]
客服反馈说：

> 你好

有些接口是不开放的，不提供使用，所以很抱歉了

开发者就按照现在的文档说明的接口使用就可以了
