### ISSUE TITLE
希望再添加几个API

### ISSUE THREAD

**Issue by niulinlnc** [007gzs/dingtalk-sdk#22]
希望添加代办事项3个API
文档地址
https://open-doc.dingtalk.com/microapp/serverapi2/gpmpiq

公告1个API
https://open-doc.dingtalk.com/microapp/serverapi2/knmd16

钉钉运动3个API
https://open-doc.dingtalk.com/microapp/serverapi2/emdh5f

钉钉日程1个API
https://open-doc.dingtalk.com/microapp/serverapi2/iqel76

**Comment by 007gzs** [comment]
已提交到master，你可以测试下，钉钉日程里面我还找到两个接口，你也可以试下能不能用

**Comment by niulinlnc** [comment]
新增的接口测试结果：
日程里的删除接口测试反馈没有权限
日程的查询接口calendar_folder_id不知道填什么，暂未测试。
待办事项的更新接口，由于更新待办没有返回数据，导致报错。
运动接口测试ok
公告接口测试ok

**Comment by niulinlnc** [comment]
以下代码有误，根据钉钉对该接口的规定，dept_id_list 与 userid_list 可不传，若传不能为空：
    def asyncsend(self, msg_body, agent_id, userid_list=(), dept_id_list=(), to_all_user=False):
        """
        企业会话消息异步发送

        :param msg_body: BodyBase 消息体
        :param agent_id: 微应用的id
        :param userid_list: 接收者的用户userid列表
        :param dept_id_list: 接收者的部门id列表
        :param to_all_user: 是否发送给企业全部用户
        :return: 任务id
        """
        userid_list = ",".join(map(to_text, userid_list))
        dept_id_list = ",".join(map(to_text, dept_id_list))

        if isinstance(msg_body, BodyBase):
            msg_body = msg_body.get_dict()
        msgtype = msg_body['msgtype']
        msgcontent = json.dumps(msg_body[msgtype])
        return self._top_request(
            'dingtalk.corp.message.corpconversation.asyncsend',
            {
                'msgtype': msgtype,
                'agent_id': agent_id,
                'msgcontent': msgcontent,
                'userid_list': userid_list,
                'dept_id_list': dept_id_list,
                'to_all_user': to_all_user
            },
            result_processor=lambda x: x['task_id']
        )

所以给dept_id_list=()会报错

**Comment by niulinlnc** [comment]
待办更新报错，单独开个issue
