### ISSUE TITLE
智能人事添加待入职还是报错

### ISSUE THREAD

**Issue by niulinlnc** [007gzs/dingtalk-sdk#28]
报错：the JSON object must be str, bytes or bytearray, not 'dict'
代码位置：
def addpreentry(self, name, mobile, pre_entry_time=None, op_userid=None, extend_info=None):
        """
        智能人事添加企业待入职员工

        :param name: 员工姓名
        :param mobile: 手机号
        :param pre_entry_time: 预期入职时间
        :param op_userid: 操作人userid
        :param extend_info: 扩展信息
        :return:
        """
        if isinstance(pre_entry_time, (datetime.date, datetime.datetime)):
            pre_entry_time = pre_entry_time.strftime(self.DATE_TIME_FORMAT)
        if isinstance(extend_info, dict):
            extend_info = json.loads(extend_info)

        return self._top_request(
            "dingtalk.oapi.smartwork.hrm.employee.addpreentry",
            optionaldict({
                "param": {
                    "name": name,
                    "mobile": mobile,
                    "pre_entry_time": pre_entry_time,
                    "op_userid": op_userid,
                    "extend_info": extend_info
                }
            })
        )

**Comment by niulinlnc** [comment]
删除 
  if isinstance(extend_info, dict):
        extend_info = json.loads(extend_info)
之后，正常。

**Comment by 007gzs** [comment]
master 试下

**Comment by niulinlnc** [comment]
就是拉的最新master测试的

**Comment by niulinlnc** [comment]
ok了
