### ISSUE TITLE
钉钉日程查询接口和删除接口出现错误

### ISSUE THREAD

**Issue by BUGLAN** [007gzs/dingtalk-sdk#32]
### 描述
接口调用失败, 返回状态码`-1`

### 截图
![image](https://user-images.githubusercontent.com/28979076/62524288-eaaf2580-b867-11e9-81a1-6f9e256f4651.png)

### 描述
接口调用失败, 返回状态码`88`(使用的是公司主管理员的钉钉user_id)

### 截图

![image](https://user-images.githubusercontent.com/28979076/62524629-8b9de080-b868-11e9-93d2-735a40514d13.png)

**Comment by 007gzs** [comment]
目前官方文档只提供了日程创建接口，查询和删除未对外提供

**Comment by BUGLAN** [comment]
目前没有实现这两个功能是吗?

**Comment by 007gzs** [comment]
官方没有把这两个功能开放出来，我只是提前实现了，以后开放出来后可以直接用

**Comment by BUGLAN** [comment]
好的, 多谢你的回复
