### ISSUE TITLE
请问AppKeyClient.role.list()没有返回值？只有logger信息 返回值为None

### ISSUE THREAD

**Issue by jiaoyuxiong** [007gzs/dingtalk-sdk#43]

**Comment by jiaoyuxiong** [comment]
def list(self, offset=0, size=20):
        """
        获取企业角色列表

        :param offset: 分页大小
        :param size: 分页偏移
        :return:
        """
        self._top_request(
            'dingtalk.corp.role.list',
            {'offset': offset, 'size': size}
        )
为什么没有return

**Comment by 007gzs** [comment]
`1.3.6` 版本中修复
