### ISSUE TITLE
多个小程序调用时, 由于缓存会出现"accessToken中包含的appKey与agentId不一致"

### ISSUE THREAD

**Issue by yovld** [007gzs/dingtalk-sdk#44]
多个小程序切换调用发信息时, 会出现以下错误, 分析应该是缓存key都相同造成的
Error code: 41020, message: accessToken中包含的appKey与agentId不一致， 无法使用当前agentId

**Comment by 007gzs** [comment]
`v1.3.7`版本中已修复
