### ISSUE TITLE
AttributeError: 'module' object has no attribute '_create_unverified_context'

### ISSUE THREAD

**Issue by donhui** [007gzs/dingtalk-sdk#6]
python 2.7.8（pip 9.0.1）安装时报错，
AttributeError: 'module' object has no attribute '_create_unverified_context'

修改了setup.py安装成功

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

**Comment by 007gzs** [comment]
1.1.8版本中修复
