### ISSUE TITLE
能否增加请假状态查询接口?

### ISSUE THREAD

**Issue by gerrysuomi** [007gzs/dingtalk-sdk#8]
版本1.1.9的考勤接口中,只有计算请假时长的接口,是否能增加查询指定用户请假状态的接口(请假状态查询接口的官方说明:https://open-doc.dingtalk.com/docs/api.htm?spm=a219a.7386797.0.0.51954a979eFk59&source=search&apiId=40614). 

另外,看它更新的官方文档(https://open-doc.dingtalk.com/microapp/serverapi2/eev437), 获得access_token好像只要appKey和appSecret,这样是否就不需要corp_id了?谢谢!

**Comment by 007gzs** [comment]
新的token获取方式可以用AppKeyClient，因为之前有一些接口用到了corp_id，所以保留了corp_id参数，如果你没有使用到这些接口这个值可以传appkey代替

**Comment by 007gzs** [comment]
1.2.2版本已添加，可以使用`client.tbdingding.dingtalk_oapi_attendance_getleavestatus()`调用
本次加的接口比较多，没有进行测试，你先试下，有问题可以直接回复

**Comment by gerrysuomi** [comment]
初步试了下新加的请假状态查询接口,看起来运行是正常的.我就把这个issue关掉了,后面如果有问题的话到时再问.谢谢.
